In [1]:
import json
import pandas as pd

# ✅ Charge le fichier JSON — remplace le nom par le tien
with open("jumia_2026-03-30T09-33-29+00-00.json", encoding="utf-8") as f:
    data = json.load(f)

# ✅ Convertit en tableau
df = pd.DataFrame(data)

# ✅ Affiche les infos générales
print("=== INFOS GÉNÉRALES ===")
print(f"Total produits : {len(df)}")
print(f"\nProduits par catégorie :")
print(df["category"].value_counts())
print(f"\nProduits par source :")
print(df["source"].value_counts())

=== INFOS GÉNÉRALES ===
Total produits : 800

Produits par catégorie :
category
smartphones    200
laptops        200
tv             200
vetements      200
Name: count, dtype: int64

Produits par source :
source
jumia    800
Name: count, dtype: int64

In [2]:
# ✅ Vérifie les valeurs manquantes
print("=== VALEURS MANQUANTES ===")
print(df.isnull().sum())

print("\n=== APERÇU DES DONNÉES ===")
df.head(10)

=== VALEURS MANQUANTES ===
name           0
price        800
category       0
source         0
url            0
timestamp      0
dtype: int64

=== APERÇU DES DONNÉES ===

,name,price,category,source,url,timestamp
0,,None,smartphones,jumia,https://www.jumia.ma/samsung-a07-67-64-gb-4-gb...,2026-03-30T09:33:34.316771
1,,None,smartphones,jumia,https://www.jumia.ma/itel-a100c-6.6-6gb-24-ram...,2026-03-30T09:33:34.330216
2,,None,smartphones,jumia,https://www.jumia.ma/samsung-galaxy-a16-8gb-25...,2026-03-30T09:33:34.332507
3,,None,smartphones,jumia,https://www.jumia.ma/xiaomi-redmi-note-15-6gb-...,2026-03-30T09:33:34.335946
4,,None,smartphones,jumia,https://www.jumia.ma/samsung-galaxy-a06-67-128...,2026-03-30T09:33:34.338220
5,,None,smartphones,jumia,https://www.jumia.ma/xiaomi-redmi-15c-6.9-4gb-...,2026-03-30T09:33:34.341774
6,,None,smartphones,jumia,https://www.jumia.ma/tecno-spark-40c-66-128go-...,2026-03-30T09:33:34.344801
7,,None,smartphones,jumia,https://www.jumia.ma/xiaomi-redmi-15c-6.9-6gb-...,2026-03-30T09:33:34.347794
8,,None,smartphones,jumia,https://www.jumia.ma/oppo-a5i-6.67-4gb128gb-ip...,2026-03-30T09:33:34.350336
9,,None,smartphones,jumia,https://www.jumia.ma/itel-a100c-6.6-8gb-35-ram...,2026-03-30T09:33:34.355366

In [3]:
# ✅ Vérifie les prix
print("=== STATISTIQUES DES PRIX ===")
print(df["price"].describe())

print("\n=== EXEMPLE DE PRODUITS ===")
for cat in df["category"].unique():
    print(f"\n--- {cat.upper()} ---")
    print(df[df["category"]==cat][["name","price"]].head(3).to_string())

=== STATISTIQUES DES PRIX ===
count       0
unique      0
top       NaN
freq      NaN
Name: price, dtype: object

=== EXEMPLE DE PRODUITS ===

--- SMARTPHONES ---
  name price
0       None
1       None
2       None

--- LAPTOPS ---
   name price
71       None
72       None
73       None

--- TV ---
    name price
125       None
126       None
127       None

--- VETEMENTS ---
    name price
210       None
211       None
212       None

In [4]:
with open("jumia_2026-03-30T10-13-56+00-00.json", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# Vérifie les valeurs manquantes
print("=== VALEURS MANQUANTES ===")
print(df.isnull().sum())

print("\n=== EXEMPLE DE PRODUITS ===")
for cat in df["category"].unique():
    print(f"\n--- {cat.upper()} ---")
    print(df[df["category"]==cat][["name","price"]].head(3).to_string())

=== VALEURS MANQUANTES ===
name            0
price        1000
category        0
source          0
url             0
timestamp       0
dtype: int64

=== EXEMPLE DE PRODUITS ===

--- SMARTPHONES ---
                                                 name price
0               A07 – 6,7" – 64 GB + 4 GB Ram – Green  None
1         A100C 6.6’’ – 6GB (2+4) RAM + 64 ROM – Noir  None
2  Galaxy A16 8GB + 256GB - Black - 2 ans de garantie  None

--- LAPTOPS ---
                                                                                                   name price
71  IdeaPad Slim 5 14IMH9 Ultra 7-155H 14" WUXGA - 16 Go + 512 Go SSD - Win 11 Home CLOUD GREY - Neuf -  None
72     ExpertBook P1503CVA - i5-13420H - 15.6" FHD - 8Go RAM + 512Go SSD - Freedos - Neuf -1An Garantie  None
73                         Optiplex 3020 MT Intel Celeron @ 2.7GHz - RAM 4Go , HDD 250Go (Remis à Neuf)  None

--- TV ---
                                                                                           name price
125               Smart TV Android 32” – Android 14.0 , Dolby Audio , HD 720 , Wi-Fi, HDMI, USB  None
126  32 QLED Full HD Smart Google TV, Dolby Audio, Design sans bordure + Support Gratuit, 32S5K  None
127                    32 HD LED Sans Cadre, HDMI, USB, Récepteur intégré + TNT + Support Mural  None

--- VETEMENTS ---
                                       name price
210  T-Shirt Pour Femmes 100% Cotton - Noir  None
211        Top Pour Femmes Polyester - Kaki  None
212       Top Pour Femmes Polyester - Beige  None

In [5]:
import json
import pandas as pd

# ✅ Charge le nouveau fichier
with open("jumia_2026-03-30T10-19-39+00-00.json", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# ✅ Vérifie les valeurs manquantes
print("=== VALEURS MANQUANTES ===")
print(df.isnull().sum())

# ✅ Vérifie les prix
print("\n=== STATISTIQUES PRIX ===")
print(df["price"].describe())

# ✅ Affiche 3 exemples par catégorie
print("\n=== EXEMPLES PAR CATÉGORIE ===")
for cat in df["category"].unique():
    print(f"\n--- {cat.upper()} ---")
    print(df[df["category"]==cat][["name","price"]].head(3).to_string())

=== VALEURS MANQUANTES ===
name           0
price        510
category       0
source         0
url            0
timestamp      0
dtype: int64

=== STATISTIQUES PRIX ===
count    490.000000
mean     201.259673
std      244.461950
min       19.000000
25%       66.750000
50%      109.000000
75%      180.000000
max      999.000000
Name: price, dtype: float64

=== EXEMPLES PAR CATÉGORIE ===

--- SMARTPHONES ---
                                                 name  price
0               A07 – 6,7" – 64 GB + 4 GB Ram – Green  949.0
1         A100C 6.6’’ – 6GB (2+4) RAM + 64 ROM – Noir  799.0
2  Galaxy A16 8GB + 256GB - Black - 2 ans de garantie    NaN

--- LAPTOPS ---
                                                                                                   name  price
71  IdeaPad Slim 5 14IMH9 Ultra 7-155H 14" WUXGA - 16 Go + 512 Go SSD - Win 11 Home CLOUD GREY - Neuf -    NaN
72     ExpertBook P1503CVA - i5-13420H - 15.6" FHD - 8Go RAM + 512Go SSD - Freedos - Neuf -1An Garantie    NaN
73                         Optiplex 3020 MT Intel Celeron @ 2.7GHz - RAM 4Go , HDD 250Go (Remis à Neuf)  399.0

--- TV ---
                                                                                           name  price
125               Smart TV Android 32” – Android 14.0 , Dolby Audio , HD 720 , Wi-Fi, HDMI, USB  999.0
126  32 QLED Full HD Smart Google TV, Dolby Audio, Design sans bordure + Support Gratuit, 32S5K    NaN
127                    32 HD LED Sans Cadre, HDMI, USB, Récepteur intégré + TNT + Support Mural  950.0

--- VETEMENTS ---
                                       name  price
210  T-Shirt Pour Femmes 100% Cotton - Noir  113.0
211        Top Pour Femmes Polyester - Kaki   86.0
212       Top Pour Femmes Polyester - Beige  124.0

In [8]:
import json
import pandas as pd

# ✅ Charge le fichier — remplace par ton nom de fichier exact
with open("jumia_2026-03-30T10-27-09+00-00.json", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# ==============================
# 1. INFOS GÉNÉRALES
# ==============================
print("=== INFOS GÉNÉRALES ===")
print(f"Total produits    : {len(df)}")
print(f"Colonnes          : {list(df.columns)}")

# ==============================
# 2. PRODUITS PAR CATÉGORIE
# ==============================
print("\n=== PRODUITS PAR CATÉGORIE ===")
print(df["category"].value_counts())

# ==============================
# 3. VALEURS MANQUANTES
# ==============================
print("\n=== VALEURS MANQUANTES ===")
print(df.isnull().sum())

# ==============================
# 4. STATISTIQUES DES PRIX
# ==============================
print("\n=== STATISTIQUES PRIX (en Dhs) ===")
print(df["price"].describe().round(2))

# ==============================
# 5. PRIX PAR CATÉGORIE
# ==============================
print("\n=== PRIX MOYEN PAR CATÉGORIE ===")
print(df.groupby("category")["price"].mean().round(2))

# ==============================
# 6. PRODUITS SANS PRIX
# ==============================
missing_price = df[df["price"].isnull()]
print(f"\n=== PRODUITS SANS PRIX : {len(missing_price)} ===")
if len(missing_price) > 0:
    print(missing_price[["name", "category", "price"]].head(5))

# ==============================
# 7. PRODUITS SANS NOM
# ==============================
missing_name = df[df["name"] == ""]
print(f"\n=== PRODUITS SANS NOM : {len(missing_name)} ===")
if len(missing_name) > 0:
    print(missing_name[["name", "category", "price"]].head(5))

# ==============================
# 8. EXEMPLES PAR CATÉGORIE
# ==============================
print("\n=== 3 EXEMPLES PAR CATÉGORIE ===")
for cat in df["category"].unique():
    print(f"\n--- {cat.upper()} ---")
    print(df[df["category"] == cat][["name", "price", "url"]].head(3).to_string())

# ==============================
# 9. VÉRIFICATION URLS
# ==============================
print("\n=== VÉRIFICATION URLS ===")
urls_valides = df["url"].str.startswith("https://www.jumia.ma").sum()
print(f"URLs valides : {urls_valides}/{len(df)}")

# ==============================
# 10. APERÇU FINAL
# ==============================
print("\n=== APERÇU FINAL ===")
df.head(10)

=== INFOS GÉNÉRALES ===
Total produits    : 1000
Colonnes          : ['name', 'price', 'category', 'source', 'url', 'timestamp']

=== PRODUITS PAR CATÉGORIE ===
category
smartphones    250
laptops        250
tv             250
vetements      250
Name: count, dtype: int64

=== VALEURS MANQUANTES ===
name          0
price        10
category      0
source        0
url           0
timestamp     0
dtype: int64

=== STATISTIQUES PRIX (en Dhs) ===
count      990.00
mean      2122.21
std       4199.93
min         19.00
25%        110.00
50%       1073.00
75%       2499.00
max      52726.00
Name: price, dtype: float64

=== PRIX MOYEN PAR CATÉGORIE ===
category
laptops        3723.68
smartphones     813.79
tv             3840.44
vetements       102.57
Name: price, dtype: float64

=== PRODUITS SANS PRIX : 10 ===
                                   name   category  price
101    Kit starter Raspberry Pi 5 + M.2    laptops    NaN
225  Pantalon Jean Charlie - Bleu Foncé  vetements    NaN
232  Pantalon Jean Charlie - Bleu Clair  vetements    NaN
235       Pantalon Jean Charlie - Dirty  vetements    NaN
335                Carte Raspberry pi 5    laptops    NaN

=== PRODUITS SANS NOM : 0 ===

=== 3 EXEMPLES PAR CATÉGORIE ===

--- SMARTPHONES ---
                                                 name   price                                                                                      url
0               A07 – 6,7" – 64 GB + 4 GB Ram – Green   949.0                   https://www.jumia.ma/samsung-a07-67-64-gb-4-gb-ram-green-67237287.html
1         A100C 6.6’’ – 6GB (2+4) RAM + 64 ROM – Noir   799.0                 https://www.jumia.ma/itel-a100c-6.6-6gb-24-ram-64-rom-noir-67607570.html
2  Galaxy A16 8GB + 256GB - Black - 2 ans de garantie  1979.0  https://www.jumia.ma/samsung-galaxy-a16-8gb-256gb-black-2-ans-de-garantie-65981498.html

--- LAPTOPS ---
                                                                                                   name    price                                                                                                                                                url
71  IdeaPad Slim 5 14IMH9 Ultra 7-155H 14" WUXGA - 16 Go + 512 Go SSD - Win 11 Home CLOUD GREY - Neuf -  10999.0  https://www.jumia.ma/lenovo-ideapad-slim-5-14imh9-ultra-7-155h-14-wuxga-16-go-512-go-ssd-win-11-home-cloud-grey-neuf-2-ans-garantie-67395823.html
72     ExpertBook P1503CVA - i5-13420H - 15.6" FHD - 8Go RAM + 512Go SSD - Freedos - Neuf -1An Garantie   5899.0                         https://www.jumia.ma/asus-expertbook-p1503cva-i5-13420h-15.6-fhd-8go-ram-512go-ssd-freedos-neuf-1an-garantie-67315766.html
73                         Optiplex 3020 MT Intel Celeron @ 2.7GHz - RAM 4Go , HDD 250Go (Remis à Neuf)    399.0                                  https://www.jumia.ma/optiplex-3020-mt-intel-celeron-at-2.7ghz-ram-4go-hdd-500go-remis-a-neuf-dell-mpg1407460.html

--- TV ---
                                                                                           name   price                                                                                                                             url
125               Smart TV Android 32” – Android 14.0 , Dolby Audio , HD 720 , Wi-Fi, HDMI, USB   999.0                    https://www.jumia.ma/tenten-smart-tv-android-32-android-14.0-dolby-audio-hd-720-wi-fi-hdmi-usb-67154065.html
126  32 QLED Full HD Smart Google TV, Dolby Audio, Design sans bordure + Support Gratuit, 32S5K  1439.0  https://www.jumia.ma/32-qled-full-hd-smart-google-tv-dolby-audio-design-sans-bordure-support-gratuit-32s5k-tcl-mpg1544971.html
127                    32 HD LED Sans Cadre, HDMI, USB, Récepteur intégré + TNT + Support Mural   950.0                      https://www.jumia.ma/visio-32-hd-led-sans-cadre-hdmi-usb-recepteur-integre-tnt-support-mural-67387271.html

--- VETEMENTS ---
                                       name  price                                                                              url
210  T-Shirt Pour Femmes 100% Cotton - Noir  113.0  https://www.jumia.ma/trendyol-t-shirt-pour-femmes-100-cotton-noir-66374557.html
211        Top Pour Femmes Polyester - Kaki   86.0       https://www.jumia.ma/trendyol-top-pour-femmes-polyester-kaki-66375066.html
212       Top Pour Femmes Polyester - Beige  124.0      https://www.jumia.ma/trendyol-top-pour-femmes-polyester-beige-66375015.html

=== VÉRIFICATION URLS ===
URLs valides : 1000/1000

=== APERÇU FINAL ===

,name,price,category,source,url,timestamp
0,"A07 – 6,7"" – 64 GB + 4 GB Ram – Green",949.0,smartphones,jumia,https://www.jumia.ma/samsung-a07-67-64-gb-4-gb...,2026-03-30T10:27:13.498929
1,A100C 6.6’’ – 6GB (2+4) RAM + 64 ROM – Noir,799.0,smartphones,jumia,https://www.jumia.ma/itel-a100c-6.6-6gb-24-ram...,2026-03-30T10:27:13.503471
2,Galaxy A16 8GB + 256GB - Black - 2 ans de gara...,1979.0,smartphones,jumia,https://www.jumia.ma/samsung-galaxy-a16-8gb-25...,2026-03-30T10:27:13.504469
3,Redmi Note 15 6GB 128GB Glacier Blue,2039.0,smartphones,jumia,https://www.jumia.ma/xiaomi-redmi-note-15-6gb-...,2026-03-30T10:27:13.506469
4,"Galaxy A06 - 6,7"" - 128 Go - 6 Go RAM – Noir",1129.0,smartphones,jumia,https://www.jumia.ma/samsung-galaxy-a06-67-128...,2026-03-30T10:27:13.508468
5,"Redmi 15C 6.9"" – 4GB + 128GB - Midnight Black",1199.0,smartphones,jumia,https://www.jumia.ma/xiaomi-redmi-15c-6.9-4gb-...,2026-03-30T10:27:13.509988
6,"Spark 40C - 6,6'' 128Go + RAM 4GB jusqu'à 16 G...",1129.0,smartphones,jumia,https://www.jumia.ma/tecno-spark-40c-66-128go-...,2026-03-30T10:27:13.512029
7,"Redmi 15C 6.9"" – 6GB + 128GB – Mint Green",1329.0,smartphones,jumia,https://www.jumia.ma/xiaomi-redmi-15c-6.9-6gb-...,2026-03-30T10:27:13.514050
8,"A5i - 6.67"" (4GB+128GB) - IP54 - 5100mAh + 45W...",1199.0,smartphones,jumia,https://www.jumia.ma/oppo-a5i-6.67-4gb128gb-ip...,2026-03-30T10:27:13.516049
9,A100C 6.6’’ – 8GB (3+5) RAM +128 ROM – Noir,929.0,smartphones,jumia,https://www.jumia.ma/itel-a100c-6.6-8gb-35-ram...,2026-03-30T10:27:13.517049

In [9]:
# ✅ Supprimer les produits sans prix
df_clean = df.dropna(subset=["price"])

print(f"Avant nettoyage : {len(df)} produits")
print(f"Après nettoyage : {len(df_clean)} produits")
print(f"Supprimés       : {len(df) - len(df_clean)} produits")

# ✅ Sauvegarder le fichier propre
df_clean.to_json(
    "jumia_clean.json",
    orient="records",
    force_ascii=False,
    indent=2
)

print("\n✅ Fichier sauvegardé : jumia_clean.json")

Avant nettoyage : 1000 produits
Après nettoyage : 990 produits
Supprimés       : 10 produits

✅ Fichier sauvegardé : jumia_clean.json

In [11]:
import json

with open(r'C:\Users\hp\Desktop\price-intelligence-platform\scrapers\data\avito_2026-03-30T12-08-43+00-00.json', 'r', encoding='utf-8') as f:
    contenu = f.read()

contenu_repare = contenu.rstrip().rstrip(',') + ']'

try:
    donnees = json.loads(contenu_repare)
    print(f"✅ {len(donnees)} entrées récupérées")
    
    with open(r'C:\Users\TonNom\Desktop\avito_repare.json', 'w', encoding='utf-8') as f:
        json.dump(donnees, f, ensure_ascii=False, indent=2)
except Exception as e:
    print(f"❌ Erreur : {e}")

✅ 134 entrées récupérées
❌ Erreur : [Errno 2] No such file or directory: 'C:\\Users\\TonNom\\Desktop\\avito_repare.json'

In [12]:
import os
print(os.path.expanduser("~"))

C:\Users\hp

In [2]:
import json
import pandas as pd

# ✅ Remplace par ton nom de fichier exact
with open("micromagma_2026-03-30T21-48-05+00-00.json", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# ✅ Nombre de produits par catégorie
print("=== PRODUITS PAR CATÉGORIE ===")
print(df["category"].value_counts())

# ✅ Valeurs manquantes
print("\n=== VALEURS MANQUANTES ===")
print(df.isnull().sum())

# ✅ Exemples par catégorie
print("\n=== 3 EXEMPLES PAR CATÉGORIE ===")
for cat in df["category"].unique():
    print(f"\n--- {cat.upper()} ---")
    print(df[df["category"]==cat][["name","price"]].head(3).to_string())

=== PRODUITS PAR CATÉGORIE ===
category
smartphones    300
laptops        212
tv              89
Name: count, dtype: int64

=== VALEURS MANQUANTES ===
name         0
price        0
category     0
source       0
url          0
timestamp    0
dtype: int64

=== 3 EXEMPLES PAR CATÉGORIE ===

--- SMARTPHONES ---
                                             name   price
0         Oppo Reno 14FS 5G 512Go 12Go RAM – Prix  4200.0
1  Samsung Galaxy S25 Ultra 256Go 12Go RAM | PRIX  9290.0
2           Oppo Reno 14F 5G 256Go 8Go RAM – Prix  3059.0

--- LAPTOPS ---
                                                                                  name    price
20  Microsoft Surface Pro 11 2024 13 pouces Snapdragon X Elite 16Go RAM 1To SSD | PRIX  19690.0
21   Apple MacBook Air 13,6 pouces M3 CPU 8 cœurs GPU 8 cœurs 256Go SSD 8Go RAM | PRIX  10999.0
22                      Lenovo IdeaPad Slim 3 15IRH8 15.6 pouces 512Go 16Go RAM – Prix   6600.0

--- TV ---
                                                                                            name   price
40                                                             Xiaomi TV A 50 pouces 2026 | PRIX  3499.0
41                                                              Xiaomi TV A Pro 32 pouces | PRIX  1399.0
42  Hisense 58 SMART TV 4K Ultra HD VIDAA - Série A6NT - 4K AI - Dolby Vision - 50-60 Hz - 58A6N  4443.0

In [3]:
import json
import pandas as pd

# ✅ Remplace par ton nom de fichier exact
with open("jumia_clean.json", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# ✅ Nombre de produits par catégorie
print("=== PRODUITS PAR CATÉGORIE ===")
print(df["category"].value_counts())

# ✅ Valeurs manquantes
print("\n=== VALEURS MANQUANTES ===")
print(df.isnull().sum())

# ✅ Exemples par catégorie
print("\n=== 3 EXEMPLES PAR CATÉGORIE ===")
for cat in df["category"].unique():
    print(f"\n--- {cat.upper()} ---")
    print(df[df["category"]==cat][["name","price"]].head(3).to_string())

=== PRODUITS PAR CATÉGORIE ===
category
smartphones    250
tv             250
laptops        245
vetements      245
Name: count, dtype: int64

=== VALEURS MANQUANTES ===
name         0
price        0
category     0
source       0
url          0
timestamp    0
dtype: int64

=== 3 EXEMPLES PAR CATÉGORIE ===

--- SMARTPHONES ---
                                                 name   price
0               A07 – 6,7" – 64 GB + 4 GB Ram – Green   949.0
1         A100C 6.6’’ – 6GB (2+4) RAM + 64 ROM – Noir   799.0
2  Galaxy A16 8GB + 256GB - Black - 2 ans de garantie  1979.0

--- LAPTOPS ---
                                                                                                   name    price
71  IdeaPad Slim 5 14IMH9 Ultra 7-155H 14" WUXGA - 16 Go + 512 Go SSD - Win 11 Home CLOUD GREY - Neuf -  10999.0
72     ExpertBook P1503CVA - i5-13420H - 15.6" FHD - 8Go RAM + 512Go SSD - Freedos - Neuf -1An Garantie   5899.0
73                         Optiplex 3020 MT Intel Celeron @ 2.7GHz - RAM 4Go , HDD 250Go (Remis à Neuf)    399.0

--- TV ---
                                                                                           name   price
124               Smart TV Android 32” – Android 14.0 , Dolby Audio , HD 720 , Wi-Fi, HDMI, USB   999.0
125  32 QLED Full HD Smart Google TV, Dolby Audio, Design sans bordure + Support Gratuit, 32S5K  1439.0
126                    32 HD LED Sans Cadre, HDMI, USB, Récepteur intégré + TNT + Support Mural   950.0

--- VETEMENTS ---
                                       name  price
209  T-Shirt Pour Femmes 100% Cotton - Noir  113.0
210        Top Pour Femmes Polyester - Kaki   86.0
211       Top Pour Femmes Polyester - Beige  124.0

In [4]:
import json
import pandas as pd

# ✅ Remplace par ton nom de fichier exact
with open("zara_2026-03-31T10-08-12+00-00.json", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# ✅ Nombre de produits par catégorie
print("=== PRODUITS PAR CATÉGORIE ===")
print(df["category"].value_counts())

# ✅ Valeurs manquantes
print("\n=== VALEURS MANQUANTES ===")
print(df.isnull().sum())

# ✅ Exemples par catégorie
print("\n=== 3 EXEMPLES PAR CATÉGORIE ===")
for cat in df["category"].unique():
    print(f"\n--- {cat.upper()} ---")
    print(df[df["category"]==cat][["name","price"]].head(3).to_string())

=== PRODUITS PAR CATÉGORIE ===
category
vetements    300
Name: count, dtype: int64

=== VALEURS MANQUANTES ===
name         0
price        0
category     0
source       0
url          0
timestamp    0
dtype: int64

=== 3 EXEMPLES PAR CATÉGORIE ===

--- VETEMENTS ---
                                       name   price
0  ROBE MI-LONGUE ASYMÉTRIQUE ZW COLLECTION   849.0
1  ROBE MI-LONGUE ASYMÉTRIQUE ZW COLLECTION   849.0
2    VESTE AJUSTÉE AVEC LAINE ZW COLLECTION  1399.0

In [5]:
import json
import pandas as pd

fichiers = {
    "jumia":      "jumia_clean.json",
    "micromagma": "micromagma_2026-03-30T21-48-05+00-00.json",
    "zara":       "zara_2026-03-31T10-08-12+00-00.json",
}

for source, fichier in fichiers.items():
    with open(fichier, encoding="utf-8") as f:
        data = json.load(f)
    df = pd.DataFrame(data)
    print(f"\n=== {source.upper()} ===")
    print(f"Total produits : {len(df)}")
    print(df["category"].value_counts())

=== JUMIA ===
Total produits : 990
category
smartphones    250
tv             250
laptops        245
vetements      245
Name: count, dtype: int64

=== MICROMAGMA ===
Total produits : 601
category
smartphones    300
laptops        212
tv              89
Name: count, dtype: int64

=== ZARA ===
Total produits : 300
category
vetements    300
Name: count, dtype: int64

In [6]:
import json
import pandas as pd

fichiers = {
    "jumia_clean.json",
    "micromagma_2026-03-30T21-48-05+00-00.json",
    "zara_2026-03-31T10-08-12+00-00.json",
}

all_data = []
for fichier in fichiers:
    with open(fichier, encoding="utf-8") as f:
        data = json.load(f)
        all_data.extend(data)
        print(f"✅ {fichier} → {len(data)} produits")

df = pd.DataFrame(all_data)

# ✅ Supprimer les doublons
df = df.drop_duplicates(subset=["url"])
df = df.dropna(subset=["price"])

print(f"\n=== RÉSUMÉ FINAL ===")
print(f"Total produits : {len(df)}")
print(f"\nPar catégorie :")
print(df["category"].value_counts())
print(f"\nPar source :")
print(df["source"].value_counts())

# ✅ Sauvegarder
df.to_json(
    "all_products.json",
    orient="records",
    force_ascii=False,
    indent=2
)
print("\n✅ Fichier fusionné sauvegardé : all_products.json")

✅ zara_2026-03-31T10-08-12+00-00.json → 300 produits
✅ jumia_clean.json → 990 produits
✅ micromagma_2026-03-30T21-48-05+00-00.json → 601 produits

=== RÉSUMÉ FINAL ===
Total produits : 1820

Par catégorie :
category
vetements      544
smartphones    537
laptops        444
tv             295
Name: count, dtype: int64

Par source :
source
jumia         919
micromagma    601
zara          300
Name: count, dtype: int64

✅ Fichier fusionné sauvegardé : all_products.json